/*
 * Generated by web/sync-assets.sh from the mod's own sounds.json. Do not edit by hand.
 *
 * A script rather than something fetched: the editor must offer the mod's tracks even
 * when index.html is opened from the filesystem, where a fetch is refused.
 */

const SHIPPED = {
  sounds: [
    "battle_music.corvault",
    "battle_music.neoflare",
    "battle_music.b2w2_tournament",
    "battle_music.lysandre",
    "battle_music.ultra_necrozma"
  ]
};
