modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"

[[mods]]
modId="cobblemon_trainers"
version="${version}"
displayName="Cobblemon Trainers"
description='''Configurable Pokémon trainers for Cobblemon.'''
logoFile="assets/cobblemon-trainers/icon.png"

[[mixins]]
config="cobblemon-trainers.mixins.json"

[[dependencies.cobblemon_trainers]]
modId="neoforge"
type="required"
versionRange="[21.1.251,)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_trainers]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_trainers]]
modId="cobblemon"
type="required"
versionRange="[1.8.1,1.9)"
ordering="AFTER"
side="BOTH"

[[dependencies.cobblemon_trainers]]
modId="kotlinforforge"
type="required"
versionRange="[5.12,)"
ordering="BEFORE"
side="BOTH"
