#!/usr/bin/env bash
# Fills web/assets/ from the mod itself.
#
# The editor needs four things the repository already holds: the intro textures a pack may
# name, the eight intros shipped with the mod, the example trainers, and the mod's own
# sounds.json - the list of tracks a trainer may ask for. None of them is copied into the
# repository - they are taken from their one source at publish time, so a track added to the
# mod is offered by the editor without anyone editing a list, and nothing can drift.
#
# Run it before opening web/index.html locally; the Pages workflow runs the same script.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
assets="$here/assets"

textures="$root/src/main/resources/assets/cobblemon-trainers/textures/gui/intro"
sounds="$root/src/main/resources/assets/cobblemon-trainers/sounds.json"
intros="$root/src/main/resources/data/cobblemon-trainers/cobblemontrainers/intro"
examples="$root/examples/cobblemonrlm/data/cobblemonrlm/cobblemontrainers/trainers"

rm -rf "$assets/intro" "$assets/intros" "$assets/examples"
mkdir -p "$assets/intro" "$assets/intros" "$assets/examples"

# The mod's own identity, taken where it already lives rather than copied into the site.
cp "$root/assets/logo.png" "$assets/logo.png"
cp "$root/src/main/resources/assets/cobblemon-trainers/icon.png" "$assets/icon.png"

cp "$textures"/*.png "$assets/intro/"
cp "$intros"/*.json "$assets/intros/"
find "$examples" -name '*.json' ! -name 'category.json' -exec cp {} "$assets/examples/" \;

# The mod's own tracks, written as a script rather than copied as data to fetch.
#
# A <script> is the one shape that also works when index.html is opened straight from disk:
# `fetch` is refused there, and the list of tracks a trainer may ask for is too central to go
# missing in the setup an author is most likely to try first. It is generated, so the one
# source stays the mod's sounds.json - and it is committed, so a fresh clone offers the tracks
# before anyone has run anything.
# `|| true` so that no match reaches the check below: `set -e` would otherwise abort right
# here, exit 1 without a word, and leave whoever ran it guessing.
keys="$(grep -oE '^  "[^"]+"' "$sounds" | tr -d ' "' || true)"
count="$(printf '%s\n' "$keys" | grep -c . || true)"
if [ "$count" -eq 0 ]; then
  echo "sync-assets: no sound keys read from $sounds - has its shape changed?" >&2
  exit 1
fi
{
  echo '/*'
  echo ' * Generated by web/sync-assets.sh from the mod'"'"'s own sounds.json. Do not edit by hand.'
  echo ' *'
  echo ' * A script rather than something fetched: the editor must offer the mod'"'"'s tracks even'
  echo ' * when index.html is opened from the filesystem, where a fetch is refused.'
  echo ' */'
  echo ''
  echo 'const SHIPPED = {'
  echo '  sounds: ['
  printf '%s\n' "$keys" | sed 's/.*/    "&",/' | sed '$ s/,$//'
  echo '  ]'
  echo '};'
} > "$here/js/shipped.js"

# The manifest is what the templates dropdown reads: a listing, since a static host has none.
{
  echo '{'
  echo '  "intros": ['
  first=1
  for file in "$assets/intros"/*.json; do
    name="$(basename "$file" .json)"
    [ $first -eq 1 ] || echo ','
    first=0
    printf '    { "id": "%s", "file": "assets/intros/%s.json" }' "$name" "$name"
  done
  echo ''
  echo '  ],'
  echo '  "trainers": ['
  first=1
  for file in "$assets/examples"/*.json; do
    name="$(basename "$file" .json)"
    [ $first -eq 1 ] || echo ','
    first=0
    printf '    { "id": "%s", "file": "assets/examples/%s.json" }' "$name" "$name"
  done
  echo ''
  echo '  ]'
  echo '}'
} > "$assets/manifest.json"

echo "web/assets: $(ls "$assets/intro" | wc -l) textures, $(ls "$assets/intros" | wc -l) intros, $(ls "$assets/examples" | wc -l) trainers, $count sounds"
